"""empty message

Revision ID: 4d0d1e781a88
Revises: 
Create Date: 2021-04-15 18:54:04.925277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d0d1e781a88'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('records',
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=200), nullable=False),
    sa.Column('created_on', sa.String(length=200), nullable=False),
    sa.Column('verified_by', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.String(length=200), nullable=False),
    sa.Column('block_hash', sa.String(length=200), nullable=False),
    sa.Column('previous_hash', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('index')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('records')
    # ### end Alembic commands ###
